# ============================================================
# ULTRA-SAFE CONFIG - GUARANTEED TO WORK (No OOM)
# Start with this, then increase settings gradually
# ============================================================

system:
  project: 'MAPSeg'
  exp_name: 'Kaggle_UltraSafe'
  wandb: False
  n_threads: 4
  seed: 0
  save_nii: False
  ckpt_dir: '/kaggle/working/checkpoints'

train:
  type: 'mae'
  lr: 2e-4
  batch_size: 1  # MINIMUM: 1 per GPU (total=2)
  niter: 300
  niter_decay: 0
  mask_ratio: 0.7
  cls_num: 8
  local_mae_patch: 8
  global_mae_patch: 4
  optimizer: 'AdamW'
  weight_decay: 0.05
  betas: [0.9, 0.95]
  print_freq: 10
  save_epoch_freq: 20
  warmup: 50
  patience: 50
  test_time: False

data:
  patch_size: [48, 48, 48]  # SMALLEST: Guaranteed to fit
  extension: '.nii.gz'
  normalize: True
  norm_perc: 99.5
  remove_bg: True
  aug: True
  aug_prob: 0.3
  mae_root: '/kaggle/working/mmwh-heart/mae_data'

model:
  depth: 6  # REDUCED: Smaller model
  embed_dim: 256  # REDUCED: Much smaller
  load_pretrain: False
  pretrain_model: null
  large_scale: False

# Memory: ~3-4 GB per GPU (very safe)
# Speed: Slower but stable
